### PR TITLE
[change] New Port: os/manifest

### PR DESCRIPTION
**Pull request by beanpole135**
This is a simple port which has one file: /var/db/current-manifest.json
This is just a copy of the TRUEOS_MANIFEST file used to do the builds, so that build manifest can be used for all sorts of things like version control, build-tagging, port build references, and more.

### CODE REVIEW

**Comment by beanpole135** [comment]
NOTE: This needs the latest fix(es) from the trueos/build repo to ensure the TrueOS build manifest is copied into the ports tree first.

**Comment by beanpole135** [comment]
Build tests just finished successfully. Needed a couple more fixes to the trueos/build repo but seems to be working fine now.

**Comment by darkfiberiru** [comment]
@beanpole135 This is already in userland-base `/var/db/trueos-manifest.json was installed by package userland-base-20190314143711`

Is there a reason we need to be able to grab just the manifest?

**Comment by darkfiberiru** [comment]
Just smaller downloads for validation?

**Comment by beanpole135** [comment]
@darkfiberiru : No, the trueos-manifest.json file in the userland-base package gets out-of-sync with the actual build the moment the source repo (os/src and os/[buildworld/buildkernel]) do not get rebuilt. This happens all the time if you do iterative builds of the ports tree without changing the source repo tag/version.
The os/manifest port is to ensure that the build manifest is *always* current, and installed to /var/db/current-manifest.json because the /var/db/trueos-manifest.json file is tied into all the buildworld/buildkernel infrastructure and cannot be easily replaced at the present time.

**Comment by beanpole135** [comment]
After 16 days without review and tons of build tests by all the builds I run, I am just going to merge it in now.

**Pull request merged**
